name: Test Redot project converter
description: Test the Redot project converter.

inputs:
  bin:
    description: The path to the Redot executable
    required: true

runs:
  using: composite
  steps:
    - name: Test 3-to-4 conversion
      shell: sh
      run: |
        mkdir converter_test
        cd converter_test
        touch project.Redot
        ../${{ inputs.bin }} --headless --validate-conversion-3to4
        cd ..
        rm converter_test -rf
