short_name = "redot"
name = "Redot Engine LTS"
major = 26
minor = 1
patch = 0
status = "beta"
status_version = 0
module_config = ""
website = "https://redotengine.org"
docs = "latest"
godot_major = 4
godot_minor = 5
godot_patch = 1
godot_status = "stable"
