name: Download Redot artifact
description: Download the Redot artifact.

inputs:
  name:
    description: The artifact name.
    default: ${{ github.job }}
  path:
    description: The path to download and extract to.
    required: true
    default: ./

runs:
  using: composite
  steps:
    - name: Download Redot Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
