blank_issues_enabled: false

contact_links:
  - name: Redot proposals
    url: https://github.com/godotengine/godot-proposals
    about: Please submit feature proposals on the Godot proposals repository, not here.

  - name: Redot documentation repository
    url: https://github.com/godotengine/godot-docs
    about: Please report issues with documentation on the Godot documentation repository, not here.

  - name: Redot community channels
    url: https://discord.gg/redot
    about: Please ask for technical support on one of the other community channels, not here.
