name: Dump Redot API
description: Dump Redot API for GDExtension

inputs:
  bin:
    description: The path to the Redot executable
    required: true

runs:
  using: composite
  steps:
    # Dump GDExtension interface and API
    - name: Dump GDExtension interface and API for Redot-cpp build
      shell: sh
      run: |
        ${{ inputs.bin }} --headless --dump-gdextension-interface --dump-extension-api
        mkdir Redot-api
        cp -f gdextension_interface.h Redot-api/
        cp -f extension_api.json Redot-api/

    - name: Upload API dump
      uses: ./.github/actions/upload-artifact
      with:
        name: Redot-api-dump
        path: ./Redot-api/*
