name: 🪲 Redot CPP
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  Redot_BASE_BRANCH: master
  # Used for the Redot-cpp checkout.
  Redot_CPP_BRANCH: 4.3

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-cpp-tests
  cancel-in-progress: true

jobs:
  Redot-cpp-tests:
    runs-on: ubuntu-20.04
    name: Build and test Redot CPP
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Checkout Redot-cpp
        uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: Redotengine/Redot-cpp
          ref: ${{ env.Redot_CPP_BRANCH }}
          path: Redot-cpp

      - name: Setup Python and SCons
        uses: ./.github/actions/Redot-deps

      - name: Setup GCC problem matcher
        uses: ammaraskar/gcc-problem-matcher@master

      - name: Download GDExtension interface and API dump
        uses: ./.github/actions/download-artifact
        with:
          name: Redot-api-dump
          path: ./Redot-cpp/gdextension

      # TODO: Enable caching when Redot-cpp has proper cache limiting.

      # - name: Restore Redot build cache
      #   uses: ./.github/actions/Redot-cache-restore
      #   with:
      #     cache-name: Redot-cpp
      #   continue-on-error: true

      - name: Build Redot-cpp test extension
        env: # Keep synced with Redot-build.
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
          SCONS_CACHE_LIMIT: 7168
        run: scons --directory=./Redot-cpp/test target=template_debug dev_build=yes verbose=yes

      # - name: Save Redot build cache
      #   uses: ./.github/actions/Redot-cache-save
      #   with:
      #     cache-name: Redot-cpp
      #   continue-on-error: true
